[[redirects]]
  from = "https://studenten-bilden-schueler.netlify.com/*"
  to = "https://studenten-bilden-schueler.de/:splat"
  force = true

[build.environment]
  NODE_VERSION = "14.5.0"
  YARN_VERSION = "1.22.4"

[build]
  publish = "public"
  command = "gatsby build"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"
